### PR TITLE
Feature/add servletv2 support

### PR DESCRIPTION
**Pull request by raseidl**

### CODE REVIEW

**Comment by jkelvie** [comment]
This looks good to me. @jperata what do you think?

**Comment by jperata** [comment]
@jkelvie Agree, nice additions and fully tested.

**Comment by raseidl** [comment]
@jkelvie @jperata thanks! great to see that my pr was merged! just one question: is it ok that I increased the version from 0.2.4-SNAPSHOT to 0.2.5-SNAPSHOT? since 0.2.4 is the latest release on maven (https://mvnrepository.com/artifact/tools.bespoken/bst4j/0.2.4)

**Comment by jperata** [comment]
Yeah, of course that makes sense.

**Pull request merged**
